export const Route = {
  FEED: 'FEED',
  FEED_TAB: 'FEED_TAB',
  ARTICLES_READ: 'ARTICLES_READ',
  ARTICLES_BY_MEDICINE: 'ARTICLES_BY_MEDICINE',
  //doctor screen and tab
  DOCTOR: 'DOCTOR',
  DOCTOR_TAB: 'DOCTOR_TAB',
  DOCTOR_MAIN_SCREEN: 'DOCTOR_MAIN_SCREEN',
  DOC_CURES: 'DOC_CURES',
  EDITPROFILE: 'EDITPROFILE',
  FILTER_DOC: 'FILTER_DOC',
  APPOINTMENT: 'APPOINTMENT',
  CHAT:'CHAT',
  VIDEOCALL:'VIDEOCALL',

  //search screen and tab
  SEARCH: 'SEARCH',
  SEARCH_TAB: 'SEARCH_TAB',
  SEARCH_INPUT:"SEARCH_INPUT",
  SEARCH_RESULT:"SEARCH_RESULT",

  //profle screen and tab
  PROFILE: 'PROFILE',
  PROFILE_TAB: 'PROFILE_TAB',
  MAIN: 'MAIN',
  FAVOURITE: 'FAVOURITE',

  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  ABOUT: 'ABOUT',
  HELP: 'HELP',
  LOGOUT: 'LOGOUT',
  NOTIFICATION: 'NOTIFICATION',
  SUBMITARTICLE: 'SUBMITARTICLE',
  TIPOFTHEDAY: 'TIPOFTHEDAY',
  INBOX:'INBOX',
  FORGETPASSWORD:'FORGETPASSWORD'
};

//feed screen and tab
